Update CI workflows (#700)
* Update CI workflows

* Fix `test_pkg.jl`

* Self-test update API workflow

diff --git a/.github/workflows/blue_style_formatter.yml b/.github/workflows/blue_style_formatter.yml
--- a/.github/workflows/blue_style_formatter.yml
+++ b/.github/workflows/blue_style_formatter.yml
@@ -1,23 +1,34 @@
 name: Format suggestions
 on:
   pull_request:
+# These permissions are needed to:
+# - Delete old caches: https://github.com/julia-actions/cache#usage
+# - Post formatting suggestions: https://github.com/reviewdog/action-suggester#required-permissions
 permissions:
+  actions: write
   contents: read
-  checks: write
-  issues: write
   pull-requests: write
 jobs:
   format:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
-      - uses: julia-actions/setup-julia@latest
+      - uses: julia-actions/setup-julia@v1
         with:
-          version: 1
-      - run: |
-          julia  -e 'using Pkg; Pkg.add(name="JuliaFormatter", version="1.0.34")'
-          julia  -e 'using JuliaFormatter; format(".", BlueStyle(); verbose=true)'
+          version: "1"
+      - uses: julia-actions/cache@v2
+      - name: Install JuliaFormatter
+        shell: julia --project=@format --color=yes {0}
+        run: |
+          using Pkg
+          Pkg.add(PackageSpec(; name="JuliaFormatter", version="1"))
+      - name: Check formatting
+        shell: julia --project=@format --color=yes {0}
+        run: |
+          using JuliaFormatter
+          format("."; verbose=true) || exit(1)
+      # Add formatting suggestions to non-draft PRs even if when "Check formatting" fails
       - uses: reviewdog/action-suggester@v1
+        if: ${{ !cancelled() && github.event_name == 'pull_request' }}
         with:
           tool_name: JuliaFormatter
-          fail_on_error: true
