Improve self-test on status-check

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -123,7 +123,7 @@ jobs:
 
   # Merge queues only wait for the required status checks to pass which are defined in the
   # repository settings under the branch protection rules. Unfortunately, the required
-  # status checks for PRs and merge queues must be the identical even though the workflows
+  # status checks for PRs and merge queues must be identical even though the workflows
   # themselves are triggered separately (i.e `pull_request` vs. `merge_group`).
   #
   # In order to have a status check which allows CI jobs to be skipped in PRs but must pass
@@ -143,5 +143,7 @@ jobs:
       - codegen-test
     runs-on: ubuntu-latest
     steps:
-      - if: ${{ github.event_name == 'merge_group' && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')  || contains(needs.*.result, 'skipped')) }}
-        run: exit 1
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')  || contains(needs.*.result, 'skipped') }}
+        run: |
+          echo ":x: One or more required jobs failed to succeed" | tee -a "$GITHUB_STEP_SUMMARY"
+          exit ${{ github.event_name == 'merge_group' && 1 || 0 }}
